// 전국 시군구 법정동 5자리 코드 마스터 — 행정안전부 법정동코드(code.go.kr) 전체자료에서
// 시군구 단위만 추출(부모 시 제외). 출처: FinanceData 미러 gist.
import type { Region } from './regions';

export const ALL_REGIONS: Region[] = [
  { lawdCd: '11110', sido: '서울', sigungu: '종로구', name: '서울 종로구' },
  { lawdCd: '11140', sido: '서울', sigungu: '중구', name: '서울 중구' },
  { lawdCd: '11170', sido: '서울', sigungu: '용산구', name: '서울 용산구' },
  { lawdCd: '11200', sido: '서울', sigungu: '성동구', name: '서울 성동구' },
  { lawdCd: '11215', sido: '서울', sigungu: '광진구', name: '서울 광진구' },
  { lawdCd: '11230', sido: '서울', sigungu: '동대문구', name: '서울 동대문구' },
  { lawdCd: '11260', sido: '서울', sigungu: '중랑구', name: '서울 중랑구' },
  { lawdCd: '11290', sido: '서울', sigungu: '성북구', name: '서울 성북구' },
  { lawdCd: '11305', sido: '서울', sigungu: '강북구', name: '서울 강북구' },
  { lawdCd: '11320', sido: '서울', sigungu: '도봉구', name: '서울 도봉구' },
  { lawdCd: '11350', sido: '서울', sigungu: '노원구', name: '서울 노원구' },
  { lawdCd: '11380', sido: '서울', sigungu: '은평구', name: '서울 은평구' },
  { lawdCd: '11410', sido: '서울', sigungu: '서대문구', name: '서울 서대문구' },
  { lawdCd: '11440', sido: '서울', sigungu: '마포구', name: '서울 마포구' },
  { lawdCd: '11470', sido: '서울', sigungu: '양천구', name: '서울 양천구' },
  { lawdCd: '11500', sido: '서울', sigungu: '강서구', name: '서울 강서구' },
  { lawdCd: '11530', sido: '서울', sigungu: '구로구', name: '서울 구로구' },
  { lawdCd: '11545', sido: '서울', sigungu: '금천구', name: '서울 금천구' },
  { lawdCd: '11560', sido: '서울', sigungu: '영등포구', name: '서울 영등포구' },
  { lawdCd: '11590', sido: '서울', sigungu: '동작구', name: '서울 동작구' },
  { lawdCd: '11620', sido: '서울', sigungu: '관악구', name: '서울 관악구' },
  { lawdCd: '11650', sido: '서울', sigungu: '서초구', name: '서울 서초구' },
  { lawdCd: '11680', sido: '서울', sigungu: '강남구', name: '서울 강남구' },
  { lawdCd: '11710', sido: '서울', sigungu: '송파구', name: '서울 송파구' },
  { lawdCd: '11740', sido: '서울', sigungu: '강동구', name: '서울 강동구' },
  { lawdCd: '26110', sido: '부산', sigungu: '중구', name: '부산 중구' },
  { lawdCd: '26140', sido: '부산', sigungu: '서구', name: '부산 서구' },
  { lawdCd: '26170', sido: '부산', sigungu: '동구', name: '부산 동구' },
  { lawdCd: '26200', sido: '부산', sigungu: '영도구', name: '부산 영도구' },
  { lawdCd: '26230', sido: '부산', sigungu: '부산진구', name: '부산 부산진구' },
  { lawdCd: '26260', sido: '부산', sigungu: '동래구', name: '부산 동래구' },
  { lawdCd: '26290', sido: '부산', sigungu: '남구', name: '부산 남구' },
  { lawdCd: '26320', sido: '부산', sigungu: '북구', name: '부산 북구' },
  { lawdCd: '26350', sido: '부산', sigungu: '해운대구', name: '부산 해운대구' },
  { lawdCd: '26380', sido: '부산', sigungu: '사하구', name: '부산 사하구' },
  { lawdCd: '26410', sido: '부산', sigungu: '금정구', name: '부산 금정구' },
  { lawdCd: '26440', sido: '부산', sigungu: '강서구', name: '부산 강서구' },
  { lawdCd: '26470', sido: '부산', sigungu: '연제구', name: '부산 연제구' },
  { lawdCd: '26500', sido: '부산', sigungu: '수영구', name: '부산 수영구' },
  { lawdCd: '26530', sido: '부산', sigungu: '사상구', name: '부산 사상구' },
  { lawdCd: '26710', sido: '부산', sigungu: '기장군', name: '부산 기장군' },
  { lawdCd: '27110', sido: '대구', sigungu: '중구', name: '대구 중구' },
  { lawdCd: '27140', sido: '대구', sigungu: '동구', name: '대구 동구' },
  { lawdCd: '27170', sido: '대구', sigungu: '서구', name: '대구 서구' },
  { lawdCd: '27200', sido: '대구', sigungu: '남구', name: '대구 남구' },
  { lawdCd: '27230', sido: '대구', sigungu: '북구', name: '대구 북구' },
  { lawdCd: '27260', sido: '대구', sigungu: '수성구', name: '대구 수성구' },
  { lawdCd: '27290', sido: '대구', sigungu: '달서구', name: '대구 달서구' },
  { lawdCd: '27710', sido: '대구', sigungu: '달성군', name: '대구 달성군' },
  { lawdCd: '28110', sido: '인천', sigungu: '중구', name: '인천 중구' },
  { lawdCd: '28140', sido: '인천', sigungu: '동구', name: '인천 동구' },
  { lawdCd: '28170', sido: '인천', sigungu: '남구', name: '인천 남구' },
  { lawdCd: '28185', sido: '인천', sigungu: '연수구', name: '인천 연수구' },
  { lawdCd: '28200', sido: '인천', sigungu: '남동구', name: '인천 남동구' },
  { lawdCd: '28237', sido: '인천', sigungu: '부평구', name: '인천 부평구' },
  { lawdCd: '28245', sido: '인천', sigungu: '계양구', name: '인천 계양구' },
  { lawdCd: '28260', sido: '인천', sigungu: '서구', name: '인천 서구' },
  { lawdCd: '28710', sido: '인천', sigungu: '강화군', name: '인천 강화군' },
  { lawdCd: '28720', sido: '인천', sigungu: '옹진군', name: '인천 옹진군' },
  { lawdCd: '29110', sido: '광주', sigungu: '동구', name: '광주 동구' },
  { lawdCd: '29140', sido: '광주', sigungu: '서구', name: '광주 서구' },
  { lawdCd: '29155', sido: '광주', sigungu: '남구', name: '광주 남구' },
  { lawdCd: '29170', sido: '광주', sigungu: '북구', name: '광주 북구' },
  { lawdCd: '29200', sido: '광주', sigungu: '광산구', name: '광주 광산구' },
  { lawdCd: '30110', sido: '대전', sigungu: '동구', name: '대전 동구' },
  { lawdCd: '30140', sido: '대전', sigungu: '중구', name: '대전 중구' },
  { lawdCd: '30170', sido: '대전', sigungu: '서구', name: '대전 서구' },
  { lawdCd: '30200', sido: '대전', sigungu: '유성구', name: '대전 유성구' },
  { lawdCd: '30230', sido: '대전', sigungu: '대덕구', name: '대전 대덕구' },
  { lawdCd: '31110', sido: '울산', sigungu: '중구', name: '울산 중구' },
  { lawdCd: '31140', sido: '울산', sigungu: '남구', name: '울산 남구' },
  { lawdCd: '31170', sido: '울산', sigungu: '동구', name: '울산 동구' },
  { lawdCd: '31200', sido: '울산', sigungu: '북구', name: '울산 북구' },
  { lawdCd: '31710', sido: '울산', sigungu: '울주군', name: '울산 울주군' },
  { lawdCd: '36110', sido: '세종', sigungu: '세종특별자치시', name: '세종특별자치시' },
  { lawdCd: '41111', sido: '경기', sigungu: '수원시 장안구', name: '경기 수원시 장안구' },
  { lawdCd: '41113', sido: '경기', sigungu: '수원시 권선구', name: '경기 수원시 권선구' },
  { lawdCd: '41115', sido: '경기', sigungu: '수원시 팔달구', name: '경기 수원시 팔달구' },
  { lawdCd: '41117', sido: '경기', sigungu: '수원시 영통구', name: '경기 수원시 영통구' },
  { lawdCd: '41131', sido: '경기', sigungu: '성남시 수정구', name: '경기 성남시 수정구' },
  { lawdCd: '41133', sido: '경기', sigungu: '성남시 중원구', name: '경기 성남시 중원구' },
  { lawdCd: '41135', sido: '경기', sigungu: '성남시 분당구', name: '경기 성남시 분당구' },
  { lawdCd: '41150', sido: '경기', sigungu: '의정부시', name: '경기 의정부시' },
  { lawdCd: '41171', sido: '경기', sigungu: '안양시 만안구', name: '경기 안양시 만안구' },
  { lawdCd: '41173', sido: '경기', sigungu: '안양시 동안구', name: '경기 안양시 동안구' },
  { lawdCd: '41190', sido: '경기', sigungu: '부천시', name: '경기 부천시' },
  { lawdCd: '41210', sido: '경기', sigungu: '광명시', name: '경기 광명시' },
  { lawdCd: '41220', sido: '경기', sigungu: '평택시', name: '경기 평택시' },
  { lawdCd: '41250', sido: '경기', sigungu: '동두천시', name: '경기 동두천시' },
  { lawdCd: '41271', sido: '경기', sigungu: '안산시 상록구', name: '경기 안산시 상록구' },
  { lawdCd: '41273', sido: '경기', sigungu: '안산시 단원구', name: '경기 안산시 단원구' },
  { lawdCd: '41281', sido: '경기', sigungu: '고양시 덕양구', name: '경기 고양시 덕양구' },
  { lawdCd: '41285', sido: '경기', sigungu: '고양시 일산동구', name: '경기 고양시 일산동구' },
  { lawdCd: '41287', sido: '경기', sigungu: '고양시 일산서구', name: '경기 고양시 일산서구' },
  { lawdCd: '41290', sido: '경기', sigungu: '과천시', name: '경기 과천시' },
  { lawdCd: '41310', sido: '경기', sigungu: '구리시', name: '경기 구리시' },
  { lawdCd: '41360', sido: '경기', sigungu: '남양주시', name: '경기 남양주시' },
  { lawdCd: '41370', sido: '경기', sigungu: '오산시', name: '경기 오산시' },
  { lawdCd: '41390', sido: '경기', sigungu: '시흥시', name: '경기 시흥시' },
  { lawdCd: '41410', sido: '경기', sigungu: '군포시', name: '경기 군포시' },
  { lawdCd: '41430', sido: '경기', sigungu: '의왕시', name: '경기 의왕시' },
  { lawdCd: '41450', sido: '경기', sigungu: '하남시', name: '경기 하남시' },
  { lawdCd: '41461', sido: '경기', sigungu: '용인시 처인구', name: '경기 용인시 처인구' },
  { lawdCd: '41463', sido: '경기', sigungu: '용인시 기흥구', name: '경기 용인시 기흥구' },
  { lawdCd: '41465', sido: '경기', sigungu: '용인시 수지구', name: '경기 용인시 수지구' },
  { lawdCd: '41480', sido: '경기', sigungu: '파주시', name: '경기 파주시' },
  { lawdCd: '41500', sido: '경기', sigungu: '이천시', name: '경기 이천시' },
  { lawdCd: '41550', sido: '경기', sigungu: '안성시', name: '경기 안성시' },
  { lawdCd: '41570', sido: '경기', sigungu: '김포시', name: '경기 김포시' },
  { lawdCd: '41590', sido: '경기', sigungu: '화성시', name: '경기 화성시' },
  { lawdCd: '41610', sido: '경기', sigungu: '광주시', name: '경기 광주시' },
  { lawdCd: '41630', sido: '경기', sigungu: '양주시', name: '경기 양주시' },
  { lawdCd: '41650', sido: '경기', sigungu: '포천시', name: '경기 포천시' },
  { lawdCd: '41670', sido: '경기', sigungu: '여주시', name: '경기 여주시' },
  { lawdCd: '41800', sido: '경기', sigungu: '연천군', name: '경기 연천군' },
  { lawdCd: '41820', sido: '경기', sigungu: '가평군', name: '경기 가평군' },
  { lawdCd: '41830', sido: '경기', sigungu: '양평군', name: '경기 양평군' },
  { lawdCd: '42110', sido: '강원', sigungu: '춘천시', name: '강원 춘천시' },
  { lawdCd: '42130', sido: '강원', sigungu: '원주시', name: '강원 원주시' },
  { lawdCd: '42150', sido: '강원', sigungu: '강릉시', name: '강원 강릉시' },
  { lawdCd: '42170', sido: '강원', sigungu: '동해시', name: '강원 동해시' },
  { lawdCd: '42190', sido: '강원', sigungu: '태백시', name: '강원 태백시' },
  { lawdCd: '42210', sido: '강원', sigungu: '속초시', name: '강원 속초시' },
  { lawdCd: '42230', sido: '강원', sigungu: '삼척시', name: '강원 삼척시' },
  { lawdCd: '42720', sido: '강원', sigungu: '홍천군', name: '강원 홍천군' },
  { lawdCd: '42730', sido: '강원', sigungu: '횡성군', name: '강원 횡성군' },
  { lawdCd: '42750', sido: '강원', sigungu: '영월군', name: '강원 영월군' },
  { lawdCd: '42760', sido: '강원', sigungu: '평창군', name: '강원 평창군' },
  { lawdCd: '42770', sido: '강원', sigungu: '정선군', name: '강원 정선군' },
  { lawdCd: '42780', sido: '강원', sigungu: '철원군', name: '강원 철원군' },
  { lawdCd: '42790', sido: '강원', sigungu: '화천군', name: '강원 화천군' },
  { lawdCd: '42800', sido: '강원', sigungu: '양구군', name: '강원 양구군' },
  { lawdCd: '42810', sido: '강원', sigungu: '인제군', name: '강원 인제군' },
  { lawdCd: '42820', sido: '강원', sigungu: '고성군', name: '강원 고성군' },
  { lawdCd: '42830', sido: '강원', sigungu: '양양군', name: '강원 양양군' },
  { lawdCd: '43111', sido: '충북', sigungu: '청주시 상당구', name: '충북 청주시 상당구' },
  { lawdCd: '43112', sido: '충북', sigungu: '청주시 서원구', name: '충북 청주시 서원구' },
  { lawdCd: '43113', sido: '충북', sigungu: '청주시 흥덕구', name: '충북 청주시 흥덕구' },
  { lawdCd: '43114', sido: '충북', sigungu: '청주시 청원구', name: '충북 청주시 청원구' },
  { lawdCd: '43130', sido: '충북', sigungu: '충주시', name: '충북 충주시' },
  { lawdCd: '43150', sido: '충북', sigungu: '제천시', name: '충북 제천시' },
  { lawdCd: '43720', sido: '충북', sigungu: '보은군', name: '충북 보은군' },
  { lawdCd: '43730', sido: '충북', sigungu: '옥천군', name: '충북 옥천군' },
  { lawdCd: '43740', sido: '충북', sigungu: '영동군', name: '충북 영동군' },
  { lawdCd: '43745', sido: '충북', sigungu: '증평군', name: '충북 증평군' },
  { lawdCd: '43750', sido: '충북', sigungu: '진천군', name: '충북 진천군' },
  { lawdCd: '43760', sido: '충북', sigungu: '괴산군', name: '충북 괴산군' },
  { lawdCd: '43770', sido: '충북', sigungu: '음성군', name: '충북 음성군' },
  { lawdCd: '43800', sido: '충북', sigungu: '단양군', name: '충북 단양군' },
  { lawdCd: '44131', sido: '충남', sigungu: '천안시 동남구', name: '충남 천안시 동남구' },
  { lawdCd: '44133', sido: '충남', sigungu: '천안시 서북구', name: '충남 천안시 서북구' },
  { lawdCd: '44150', sido: '충남', sigungu: '공주시', name: '충남 공주시' },
  { lawdCd: '44180', sido: '충남', sigungu: '보령시', name: '충남 보령시' },
  { lawdCd: '44200', sido: '충남', sigungu: '아산시', name: '충남 아산시' },
  { lawdCd: '44210', sido: '충남', sigungu: '서산시', name: '충남 서산시' },
  { lawdCd: '44230', sido: '충남', sigungu: '논산시', name: '충남 논산시' },
  { lawdCd: '44250', sido: '충남', sigungu: '계룡시', name: '충남 계룡시' },
  { lawdCd: '44270', sido: '충남', sigungu: '당진시', name: '충남 당진시' },
  { lawdCd: '44710', sido: '충남', sigungu: '금산군', name: '충남 금산군' },
  { lawdCd: '44760', sido: '충남', sigungu: '부여군', name: '충남 부여군' },
  { lawdCd: '44770', sido: '충남', sigungu: '서천군', name: '충남 서천군' },
  { lawdCd: '44790', sido: '충남', sigungu: '청양군', name: '충남 청양군' },
  { lawdCd: '44800', sido: '충남', sigungu: '홍성군', name: '충남 홍성군' },
  { lawdCd: '44810', sido: '충남', sigungu: '예산군', name: '충남 예산군' },
  { lawdCd: '44825', sido: '충남', sigungu: '태안군', name: '충남 태안군' },
  { lawdCd: '45111', sido: '전북', sigungu: '전주시 완산구', name: '전북 전주시 완산구' },
  { lawdCd: '45113', sido: '전북', sigungu: '전주시 덕진구', name: '전북 전주시 덕진구' },
  { lawdCd: '45130', sido: '전북', sigungu: '군산시', name: '전북 군산시' },
  { lawdCd: '45140', sido: '전북', sigungu: '익산시', name: '전북 익산시' },
  { lawdCd: '45180', sido: '전북', sigungu: '정읍시', name: '전북 정읍시' },
  { lawdCd: '45190', sido: '전북', sigungu: '남원시', name: '전북 남원시' },
  { lawdCd: '45210', sido: '전북', sigungu: '김제시', name: '전북 김제시' },
  { lawdCd: '45710', sido: '전북', sigungu: '완주군', name: '전북 완주군' },
  { lawdCd: '45720', sido: '전북', sigungu: '진안군', name: '전북 진안군' },
  { lawdCd: '45730', sido: '전북', sigungu: '무주군', name: '전북 무주군' },
  { lawdCd: '45740', sido: '전북', sigungu: '장수군', name: '전북 장수군' },
  { lawdCd: '45750', sido: '전북', sigungu: '임실군', name: '전북 임실군' },
  { lawdCd: '45770', sido: '전북', sigungu: '순창군', name: '전북 순창군' },
  { lawdCd: '45790', sido: '전북', sigungu: '고창군', name: '전북 고창군' },
  { lawdCd: '45800', sido: '전북', sigungu: '부안군', name: '전북 부안군' },
  { lawdCd: '46110', sido: '전남', sigungu: '목포시', name: '전남 목포시' },
  { lawdCd: '46130', sido: '전남', sigungu: '여수시', name: '전남 여수시' },
  { lawdCd: '46150', sido: '전남', sigungu: '순천시', name: '전남 순천시' },
  { lawdCd: '46170', sido: '전남', sigungu: '나주시', name: '전남 나주시' },
  { lawdCd: '46230', sido: '전남', sigungu: '광양시', name: '전남 광양시' },
  { lawdCd: '46710', sido: '전남', sigungu: '담양군', name: '전남 담양군' },
  { lawdCd: '46720', sido: '전남', sigungu: '곡성군', name: '전남 곡성군' },
  { lawdCd: '46730', sido: '전남', sigungu: '구례군', name: '전남 구례군' },
  { lawdCd: '46770', sido: '전남', sigungu: '고흥군', name: '전남 고흥군' },
  { lawdCd: '46780', sido: '전남', sigungu: '보성군', name: '전남 보성군' },
  { lawdCd: '46790', sido: '전남', sigungu: '화순군', name: '전남 화순군' },
  { lawdCd: '46800', sido: '전남', sigungu: '장흥군', name: '전남 장흥군' },
  { lawdCd: '46810', sido: '전남', sigungu: '강진군', name: '전남 강진군' },
  { lawdCd: '46820', sido: '전남', sigungu: '해남군', name: '전남 해남군' },
  { lawdCd: '46830', sido: '전남', sigungu: '영암군', name: '전남 영암군' },
  { lawdCd: '46840', sido: '전남', sigungu: '무안군', name: '전남 무안군' },
  { lawdCd: '46860', sido: '전남', sigungu: '함평군', name: '전남 함평군' },
  { lawdCd: '46870', sido: '전남', sigungu: '영광군', name: '전남 영광군' },
  { lawdCd: '46880', sido: '전남', sigungu: '장성군', name: '전남 장성군' },
  { lawdCd: '46890', sido: '전남', sigungu: '완도군', name: '전남 완도군' },
  { lawdCd: '46900', sido: '전남', sigungu: '진도군', name: '전남 진도군' },
  { lawdCd: '46910', sido: '전남', sigungu: '신안군', name: '전남 신안군' },
  { lawdCd: '47111', sido: '경북', sigungu: '포항시 남구', name: '경북 포항시 남구' },
  { lawdCd: '47113', sido: '경북', sigungu: '포항시 북구', name: '경북 포항시 북구' },
  { lawdCd: '47130', sido: '경북', sigungu: '경주시', name: '경북 경주시' },
  { lawdCd: '47150', sido: '경북', sigungu: '김천시', name: '경북 김천시' },
  { lawdCd: '47170', sido: '경북', sigungu: '안동시', name: '경북 안동시' },
  { lawdCd: '47190', sido: '경북', sigungu: '구미시', name: '경북 구미시' },
  { lawdCd: '47210', sido: '경북', sigungu: '영주시', name: '경북 영주시' },
  { lawdCd: '47230', sido: '경북', sigungu: '영천시', name: '경북 영천시' },
  { lawdCd: '47250', sido: '경북', sigungu: '상주시', name: '경북 상주시' },
  { lawdCd: '47280', sido: '경북', sigungu: '문경시', name: '경북 문경시' },
  { lawdCd: '47290', sido: '경북', sigungu: '경산시', name: '경북 경산시' },
  { lawdCd: '47720', sido: '경북', sigungu: '군위군', name: '경북 군위군' },
  { lawdCd: '47730', sido: '경북', sigungu: '의성군', name: '경북 의성군' },
  { lawdCd: '47750', sido: '경북', sigungu: '청송군', name: '경북 청송군' },
  { lawdCd: '47760', sido: '경북', sigungu: '영양군', name: '경북 영양군' },
  { lawdCd: '47770', sido: '경북', sigungu: '영덕군', name: '경북 영덕군' },
  { lawdCd: '47820', sido: '경북', sigungu: '청도군', name: '경북 청도군' },
  { lawdCd: '47830', sido: '경북', sigungu: '고령군', name: '경북 고령군' },
  { lawdCd: '47840', sido: '경북', sigungu: '성주군', name: '경북 성주군' },
  { lawdCd: '47850', sido: '경북', sigungu: '칠곡군', name: '경북 칠곡군' },
  { lawdCd: '47900', sido: '경북', sigungu: '예천군', name: '경북 예천군' },
  { lawdCd: '47920', sido: '경북', sigungu: '봉화군', name: '경북 봉화군' },
  { lawdCd: '47930', sido: '경북', sigungu: '울진군', name: '경북 울진군' },
  { lawdCd: '47940', sido: '경북', sigungu: '울릉군', name: '경북 울릉군' },
  { lawdCd: '48121', sido: '경남', sigungu: '창원시 의창구', name: '경남 창원시 의창구' },
  { lawdCd: '48123', sido: '경남', sigungu: '창원시 성산구', name: '경남 창원시 성산구' },
  { lawdCd: '48125', sido: '경남', sigungu: '창원시 마산합포구', name: '경남 창원시 마산합포구' },
  { lawdCd: '48127', sido: '경남', sigungu: '창원시 마산회원구', name: '경남 창원시 마산회원구' },
  { lawdCd: '48129', sido: '경남', sigungu: '창원시 진해구', name: '경남 창원시 진해구' },
  { lawdCd: '48170', sido: '경남', sigungu: '진주시', name: '경남 진주시' },
  { lawdCd: '48220', sido: '경남', sigungu: '통영시', name: '경남 통영시' },
  { lawdCd: '48240', sido: '경남', sigungu: '사천시', name: '경남 사천시' },
  { lawdCd: '48250', sido: '경남', sigungu: '김해시', name: '경남 김해시' },
  { lawdCd: '48270', sido: '경남', sigungu: '밀양시', name: '경남 밀양시' },
  { lawdCd: '48310', sido: '경남', sigungu: '거제시', name: '경남 거제시' },
  { lawdCd: '48330', sido: '경남', sigungu: '양산시', name: '경남 양산시' },
  { lawdCd: '48720', sido: '경남', sigungu: '의령군', name: '경남 의령군' },
  { lawdCd: '48730', sido: '경남', sigungu: '함안군', name: '경남 함안군' },
  { lawdCd: '48740', sido: '경남', sigungu: '창녕군', name: '경남 창녕군' },
  { lawdCd: '48820', sido: '경남', sigungu: '고성군', name: '경남 고성군' },
  { lawdCd: '48840', sido: '경남', sigungu: '남해군', name: '경남 남해군' },
  { lawdCd: '48850', sido: '경남', sigungu: '하동군', name: '경남 하동군' },
  { lawdCd: '48860', sido: '경남', sigungu: '산청군', name: '경남 산청군' },
  { lawdCd: '48870', sido: '경남', sigungu: '함양군', name: '경남 함양군' },
  { lawdCd: '48880', sido: '경남', sigungu: '거창군', name: '경남 거창군' },
  { lawdCd: '48890', sido: '경남', sigungu: '합천군', name: '경남 합천군' },
  { lawdCd: '50110', sido: '제주', sigungu: '제주시', name: '제주 제주시' },
  { lawdCd: '50130', sido: '제주', sigungu: '서귀포시', name: '제주 서귀포시' },
];
